# Generated by Django 3.2 on 2021-04-17 06:12

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email_Id', models.EmailField(max_length=100)),
                ('Contact_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=5000)),
                ('User_Id', models.CharField(max_length=6)),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Semester', models.IntegerField(max_length=2)),
                ('Intake', models.IntegerField(max_length=4)),
                ('Discription', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email_Id', models.EmailField(max_length=100)),
                ('Years_Of_Experience', models.FloatField(max_length=3)),
                ('Joining_Date', models.DateField()),
                ('Designation', models.CharField(max_length=200)),
                ('Academic_Qualification', models.CharField(max_length=500)),
                ('Contact_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Duration', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Email_Id', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Enrollment_No', models.CharField(max_length=10)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(max_length=100)),
                ('Gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'others')])),
                ('Admission_Year', models.IntegerField(max_length=4)),
                ('Contact_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Major_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.major')),
                ('Programme_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.programme')),
                ('School_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.school')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=300)),
                ('Contact_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=2000)),
                ('Deadline', models.DateTimeField()),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
                ('Faculty_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField()),
                ('Status', models.BooleanField()),
                ('Grade', models.CharField(max_length=2)),
                ('Content', models.CharField(max_length=10000)),
                ('Faculty_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.faculty')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.student')),
                ('Task_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.task')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField()),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField()),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='University_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.university'),
        ),
        migrations.AddField(
            model_name='school',
            name='University_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.university'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField()),
                ('Content', models.CharField(max_length=10000)),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
                ('Faculty_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Q_and_A_University_wide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Id', models.IntegerField(max_length=6, unique=True)),
                ('Answer_Id', models.IntegerField(max_length=6, unique=True)),
                ('Type', models.CharField(max_length=1)),
                ('Content', models.CharField(max_length=2000)),
                ('Timestamp', models.DateTimeField()),
                ('User_Id', models.CharField(max_length=6)),
                ('University_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.university')),
            ],
        ),
        migrations.CreateModel(
            name='Q_and_A_Course_wise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Id', models.IntegerField(max_length=6, unique=True)),
                ('Answer_Id', models.IntegerField(max_length=6, unique=True)),
                ('Type', models.CharField(max_length=1)),
                ('Content', models.CharField(max_length=2000)),
                ('Timestamp', models.DateTimeField()),
                ('User_Id', models.CharField(max_length=6)),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='School_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.school'),
        ),
        migrations.AddField(
            model_name='major',
            name='Programme_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.programme'),
        ),
        migrations.CreateModel(
            name='Faculty_Feedback',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Rating', models.FloatField(max_length=3)),
                ('TimeStamp', models.DateTimeField()),
                ('Description', models.CharField(max_length=1000)),
                ('Faculty_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.faculty')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.student')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField()),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
                ('Faculty_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('Admin_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.admin')),
                ('Faculty_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Feedback',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Rating', models.FloatField(max_length=3)),
                ('TimeStamp', models.DateTimeField()),
                ('Description', models.CharField(max_length=1000)),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField()),
                ('Admin_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.admin')),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Major_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.major'),
        ),
        migrations.AddField(
            model_name='course',
            name='Programme_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.programme'),
        ),
        migrations.AddField(
            model_name='course',
            name='School_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.school'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('Id', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('User_Id', models.CharField(max_length=6)),
                ('Content', models.CharField(max_length=2000)),
                ('Timestamp', models.DateTimeField()),
                ('Status', models.BooleanField()),
                ('Admin_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=2000)),
                ('Timestamp', models.DateTimeField()),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.student')),
                ('Submission_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.submission')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='School_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.school'),
        ),
    ]
