# Generated by Django 3.2 on 2021-04-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_alter_submission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='Title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
