# Generated by Django 3.2 on 2021-04-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_resource_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q_and_a_course_wise',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='q_and_a_university_wide',
            name='Type',
        ),
        migrations.AddField(
            model_name='q_and_a_course_wise',
            name='Question',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='q_and_a_university_wide',
            name='Question',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='q_and_a_course_wise',
            name='Answer_Id',
            field=models.IntegerField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='q_and_a_course_wise',
            name='Question_Id',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='q_and_a_university_wide',
            name='Answer_Id',
            field=models.IntegerField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='q_and_a_university_wide',
            name='Question_Id',
            field=models.IntegerField(max_length=6),
        ),
    ]
