# Generated by Django 3.2 on 2021-04-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_auto_20210419_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='University_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.university'),
        ),
    ]
