# Generated by Django 3.2.1 on 2021-05-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_faculty_university_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='peer_mode',
            field=models.BooleanField(default=False),
        ),
    ]
