# Generated by Django 3.2.1 on 2021-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0008_task_peer_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_feedback',
            name='Id',
        ),
        migrations.AddField(
            model_name='faculty_feedback',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
