# Generated by Django 3.2.1 on 2021-05-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0009_auto_20210506_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_feedback',
            name='Course_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.course'),
        ),
    ]
