# Generated by Django 3.2.1 on 2021-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0010_faculty_feedback_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_feedback',
            name='Id',
        ),
        migrations.AddField(
            model_name='course_feedback',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
