# Generated by Django 3.2.1 on 2021-05-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0011_auto_20210506_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='Faculty_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.faculty'),
        ),
    ]
