# Generated by Django 3.2.1 on 2021-05-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0012_alter_submission_faculty_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='Id',
        ),
        migrations.AddField(
            model_name='submission',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
