# Generated by Django 3.2.1 on 2021-05-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0013_auto_20210507_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Id',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
