# Generated by Django 3.2.1 on 2021-05-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0015_task_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='Added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
